### Get all notes
GET http://localhost:3001/api/notes

### Get a note
GET http://localhost:3001/api/notes/1


### Add a new note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "This is a new note",
    "important": true
}

### Delete a note
DELETE http://localhost:3001/api/notes/4